// <auto-generated />
using LabReferenceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabReferenceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708001706_SeedReferenceData")]
    partial class SeedReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabReferenceApi.Models.Biomarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClinicalContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Panel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Biomarkers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicalContext = "White blood cells are the primary cells of the immune system. Elevated counts (leukocytosis) may indicate infection, inflammation, leukemia, or corticosteroid use. Low counts (leukopenia) increase infection risk and may indicate bone marrow suppression, viral illness, or autoimmune conditions.",
                            DisplayName = "White Blood Cells (WBC)",
                            Name = "WBC",
                            Panel = "CBC"
                        },
                        new
                        {
                            Id = 2,
                            ClinicalContext = "Red blood cells carry oxygen throughout the body via hemoglobin. Low counts suggest anemia from blood loss, hemolysis, or decreased production. Elevated counts (polycythemia) may indicate dehydration, chronic hypoxia, or polycythemia vera.",
                            DisplayName = "Red Blood Cells (RBC)",
                            Name = "RBC",
                            Panel = "CBC"
                        },
                        new
                        {
                            Id = 3,
                            ClinicalContext = "Hemoglobin is the oxygen-carrying protein in red blood cells. Low values indicate anemia; causes include iron deficiency, B12/folate deficiency, chronic disease, hemolysis, or blood loss. Critically low levels impair oxygen delivery to tissues.",
                            DisplayName = "Hemoglobin (Hgb)",
                            Name = "Hemoglobin",
                            Panel = "CBC"
                        },
                        new
                        {
                            Id = 4,
                            ClinicalContext = "Hematocrit is the percentage of blood volume occupied by red blood cells. It parallels hemoglobin trends and is used to assess anemia severity and guide transfusion decisions.",
                            DisplayName = "Hematocrit (Hct)",
                            Name = "Hematocrit",
                            Panel = "CBC"
                        },
                        new
                        {
                            Id = 5,
                            ClinicalContext = "Platelets are essential for primary hemostasis. Thrombocytopenia (low platelets) increases bleeding risk and may result from ITP, medications, bone marrow disease, or sepsis. Thrombocytosis may indicate reactive processes or essential thrombocythemia.",
                            DisplayName = "Platelets (PLT)",
                            Name = "Platelets",
                            Panel = "CBC"
                        },
                        new
                        {
                            Id = 6,
                            ClinicalContext = "MCV measures the average size of red blood cells. Low MCV (microcytic) suggests iron deficiency or thalassemia. High MCV (macrocytic) suggests B12/folate deficiency, liver disease, or hypothyroidism. Normal MCV with anemia points to chronic disease or acute blood loss.",
                            DisplayName = "Mean Corpuscular Volume (MCV)",
                            Name = "MCV",
                            Panel = "CBC"
                        },
                        new
                        {
                            Id = 7,
                            ClinicalContext = "MCH is the average amount of hemoglobin per red blood cell. It typically follows MCV trends and helps classify anemia as hypochromic (iron deficiency) or normochromic.",
                            DisplayName = "Mean Corpuscular Hemoglobin (MCH)",
                            Name = "MCH",
                            Panel = "CBC"
                        },
                        new
                        {
                            Id = 8,
                            ClinicalContext = "MCHC measures hemoglobin concentration relative to cell size. Low MCHC (hypochromia) is characteristic of iron deficiency anemia. Elevated MCHC may indicate hereditary spherocytosis or significant lipemia.",
                            DisplayName = "Mean Corpuscular Hemoglobin Concentration (MCHC)",
                            Name = "MCHC",
                            Panel = "CBC"
                        },
                        new
                        {
                            Id = 9,
                            ClinicalContext = "RDW reflects variation in red blood cell size (anisocytosis). Elevated RDW is an early marker of iron deficiency, B12/folate deficiency, or mixed nutritional anemias. A high RDW with normal MCV may precede other CBC changes.",
                            DisplayName = "Red Cell Distribution Width (RDW)",
                            Name = "RDW",
                            Panel = "CBC"
                        },
                        new
                        {
                            Id = 10,
                            ClinicalContext = "Sodium is the primary extracellular cation and regulates fluid balance. Hyponatremia causes neurological symptoms and may result from SIADH, heart failure, cirrhosis, or excessive water intake. Hypernatremia indicates dehydration or diabetes insipidus.",
                            DisplayName = "Sodium (Na)",
                            Name = "Sodium",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 11,
                            ClinicalContext = "Potassium is critical for cardiac and neuromuscular function. Hypokalemia can cause arrhythmias, muscle weakness, and ileus. Hyperkalemia, particularly above 6.5 mEq/L, is a medical emergency due to risk of fatal cardiac arrhythmia.",
                            DisplayName = "Potassium (K)",
                            Name = "Potassium",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 12,
                            ClinicalContext = "Chloride is the primary extracellular anion, closely linked to sodium balance. Abnormalities are often secondary to acid-base disturbances. Hypochloremia occurs in metabolic alkalosis; hyperchloremia occurs in hyperchloremic metabolic acidosis or dehydration.",
                            DisplayName = "Chloride (Cl)",
                            Name = "Chloride",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 13,
                            ClinicalContext = "Serum CO2 primarily reflects bicarbonate and is used to assess acid-base status. Low CO2 suggests metabolic acidosis (DKA, renal failure, lactic acidosis). High CO2 suggests metabolic alkalosis (vomiting, diuretic use, hyperaldosteronism).",
                            DisplayName = "Carbon Dioxide / Bicarbonate (CO2)",
                            Name = "CO2",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 14,
                            ClinicalContext = "Calcium is essential for neuromuscular function, cardiac contractility, and bone mineralization. Hypocalcemia causes tetany, seizures, and prolonged QT. Hypercalcemia may indicate hyperparathyroidism, malignancy, sarcoidosis, or excess vitamin D.",
                            DisplayName = "Calcium (Ca)",
                            Name = "Calcium",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 15,
                            ClinicalContext = "BUN reflects protein catabolism and renal urea excretion. Elevated BUN indicates renal impairment, dehydration, high protein intake, GI bleeding, or catabolic states. The BUN:Creatinine ratio helps differentiate prerenal from intrinsic renal causes.",
                            DisplayName = "Blood Urea Nitrogen (BUN)",
                            Name = "BUN",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 16,
                            ClinicalContext = "Creatinine is a byproduct of muscle metabolism filtered by the kidneys. It is a more specific indicator of renal function than BUN alone. Rising creatinine indicates declining GFR. Reference ranges differ by sex due to differences in muscle mass.",
                            DisplayName = "Creatinine (Cr)",
                            Name = "Creatinine",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 17,
                            ClinicalContext = "eGFR estimates kidney filtration capacity, calculated from creatinine, age, and sex. Values below 60 for more than 3 months indicate chronic kidney disease. Values below 15 indicate kidney failure. eGFR is used to stage CKD and dose renally cleared medications.",
                            DisplayName = "Estimated Glomerular Filtration Rate (eGFR)",
                            Name = "eGFR",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 18,
                            ClinicalContext = "Fasting glucose is the primary screening test for diabetes and prediabetes. Values 100–125 mg/dL indicate impaired fasting glucose (prediabetes). Values ≥126 mg/dL on two occasions confirm diabetes. Critical hypoglycemia causes altered consciousness and seizures.",
                            DisplayName = "Glucose (fasting)",
                            Name = "Glucose",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 19,
                            ClinicalContext = "AST is found in hepatocytes, cardiac muscle, and skeletal muscle. Elevated AST indicates hepatocellular injury, myocardial infarction, or muscle damage. The AST:ALT ratio is useful — a ratio >2 suggests alcoholic liver disease; a ratio <1 suggests viral hepatitis.",
                            DisplayName = "Aspartate Aminotransferase (AST)",
                            Name = "AST",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 20,
                            ClinicalContext = "ALT is a liver-specific enzyme and the preferred marker of hepatocellular injury. Markedly elevated ALT (>10× normal) suggests acute viral hepatitis, ischemic hepatitis, or drug-induced liver injury. Mildly elevated ALT is common in NAFLD and metabolic syndrome.",
                            DisplayName = "Alanine Aminotransferase (ALT)",
                            Name = "ALT",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 21,
                            ClinicalContext = "ALP is produced in the liver, bone, intestine, and placenta. Isolated ALP elevation suggests cholestatic liver disease or bone disorders (Paget disease, bone metastases). Concurrent elevation of ALP and GGT confirms hepatic origin.",
                            DisplayName = "Alkaline Phosphatase (ALP)",
                            Name = "ALP",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 22,
                            ClinicalContext = "Bilirubin is a breakdown product of heme. Elevated total bilirubin causes jaundice. Pre-hepatic elevation suggests hemolysis; hepatic elevation suggests hepatocellular disease or conjugation defects (Gilbert syndrome); post-hepatic elevation suggests biliary obstruction.",
                            DisplayName = "Total Bilirubin (T. Bili)",
                            Name = "Total Bilirubin",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 23,
                            ClinicalContext = "Total protein reflects albumin plus globulins. Low values indicate malnutrition, malabsorption, liver disease, or protein-losing enteropathy/nephropathy. High values may indicate dehydration or paraprotein production (multiple myeloma).",
                            DisplayName = "Total Protein",
                            Name = "Total Protein",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 24,
                            ClinicalContext = "Albumin is the most abundant plasma protein and a marker of nutritional status and hepatic synthetic function. Low albumin is associated with poor outcomes in hospitalized patients. It also affects interpretation of other labs — notably calcium, which is partly albumin-bound.",
                            DisplayName = "Albumin",
                            Name = "Albumin",
                            Panel = "CMP"
                        },
                        new
                        {
                            Id = 25,
                            ClinicalContext = "Total cholesterol is the sum of LDL, HDL, and VLDL cholesterol. Elevated levels are a modifiable risk factor for atherosclerotic cardiovascular disease (ASCVD). Interpretation is most meaningful in the context of the full lipid profile and cardiovascular risk factors.",
                            DisplayName = "Total Cholesterol",
                            Name = "Total Cholesterol",
                            Panel = "Lipid Panel"
                        },
                        new
                        {
                            Id = 26,
                            ClinicalContext = "LDL ('bad' cholesterol) is the primary atherogenic lipoprotein. Elevated LDL drives atherosclerotic plaque formation. Target LDL depends on cardiovascular risk category — high-risk patients (prior ASCVD, diabetes) require levels <70 mg/dL. Statins are the primary treatment for elevated LDL.",
                            DisplayName = "LDL Cholesterol",
                            Name = "LDL",
                            Panel = "Lipid Panel"
                        },
                        new
                        {
                            Id = 27,
                            ClinicalContext = "HDL ('good' cholesterol) facilitates reverse cholesterol transport from arterial walls to the liver. Low HDL is an independent cardiovascular risk factor. HDL reference ranges differ by sex — women typically have higher HDL than men. Levels above 60 mg/dL are considered cardioprotective.",
                            DisplayName = "HDL Cholesterol",
                            Name = "HDL",
                            Panel = "Lipid Panel"
                        },
                        new
                        {
                            Id = 28,
                            ClinicalContext = "Triglycerides are the primary storage form of fat. Elevated triglycerides (hypertriglyceridemia) are associated with ASCVD risk, metabolic syndrome, and pancreatitis at very high levels (>500 mg/dL). Triglycerides are most accurate on a fasting sample.",
                            DisplayName = "Triglycerides (TG)",
                            Name = "Triglycerides",
                            Panel = "Lipid Panel"
                        },
                        new
                        {
                            Id = 29,
                            ClinicalContext = "Non-HDL cholesterol is calculated as Total Cholesterol minus HDL and represents all atherogenic lipoproteins (LDL + VLDL + IDL + Lp(a)). It is a stronger predictor of ASCVD risk than LDL alone and does not require fasting. Target is typically 30 mg/dL above the LDL goal.",
                            DisplayName = "Non-HDL Cholesterol (calculated)",
                            Name = "Non-HDL Cholesterol",
                            Panel = "Lipid Panel"
                        },
                        new
                        {
                            Id = 30,
                            ClinicalContext = "TSH is the most sensitive test for thyroid dysfunction. Low TSH indicates hyperthyroidism (or TSH suppression from exogenous thyroid hormone). High TSH indicates primary hypothyroidism. Reference ranges are slightly broader in older adults. TSH should be the first-line thyroid test.",
                            DisplayName = "Thyroid Stimulating Hormone (TSH)",
                            Name = "TSH",
                            Panel = "Thyroid"
                        },
                        new
                        {
                            Id = 31,
                            ClinicalContext = "Free T3 is the biologically active thyroid hormone. Elevated Free T3 confirms hyperthyroidism, particularly T3 toxicosis. Low Free T3 may occur in severe non-thyroidal illness (low T3 syndrome) without true hypothyroidism. Useful when TSH is suppressed but Free T4 is normal.",
                            DisplayName = "Free Triiodothyronine (Free T3)",
                            Name = "Free T3",
                            Panel = "Thyroid"
                        },
                        new
                        {
                            Id = 32,
                            ClinicalContext = "Free T4 is the primary secretory product of the thyroid gland and the precursor to the active T3. Low Free T4 with high TSH confirms primary hypothyroidism. Low Free T4 with low TSH suggests central (pituitary or hypothalamic) hypothyroidism.",
                            DisplayName = "Free Thyroxine (Free T4)",
                            Name = "Free T4",
                            Panel = "Thyroid"
                        },
                        new
                        {
                            Id = 33,
                            ClinicalContext = "CRP is an acute-phase reactant produced by the liver in response to inflammation or infection. High-sensitivity CRP (hsCRP) stratifies cardiovascular risk. Markedly elevated CRP (>10 mg/L) suggests active bacterial infection, autoimmune flare, or tissue injury. CRP rises within hours and normalizes quickly with resolution.",
                            DisplayName = "C-Reactive Protein (CRP)",
                            Name = "CRP",
                            Panel = "Inflammatory Markers"
                        },
                        new
                        {
                            Id = 34,
                            ClinicalContext = "ESR measures the rate at which red blood cells settle in a tube and is a nonspecific marker of inflammation. It rises more slowly than CRP and remains elevated longer. ESR is useful for monitoring conditions like polymyalgia rheumatica, temporal arteritis, and multiple myeloma.",
                            DisplayName = "Erythrocyte Sedimentation Rate (ESR)",
                            Name = "ESR",
                            Panel = "Inflammatory Markers"
                        },
                        new
                        {
                            Id = 35,
                            ClinicalContext = "Ferritin is the primary intracellular iron storage protein. Low ferritin is the earliest and most specific marker of iron deficiency. Ferritin is also an acute-phase reactant — elevated ferritin may reflect inflammation, liver disease, or malignancy rather than iron overload, so clinical context is essential.",
                            DisplayName = "Ferritin",
                            Name = "Ferritin",
                            Panel = "Inflammatory Markers"
                        },
                        new
                        {
                            Id = 36,
                            ClinicalContext = "25-hydroxyvitamin D is the best indicator of vitamin D status. Deficiency (<20 ng/mL) is associated with bone disease, muscle weakness, and immune dysfunction. Insufficiency (20–29 ng/mL) is common and may warrant supplementation. Toxicity (>100 ng/mL) can cause hypercalcemia.",
                            DisplayName = "25-Hydroxyvitamin D (Vitamin D)",
                            Name = "Vitamin D",
                            Panel = "Vitamins & Minerals"
                        },
                        new
                        {
                            Id = 37,
                            ClinicalContext = "Vitamin B12 is essential for DNA synthesis and myelin maintenance. Deficiency causes macrocytic anemia, peripheral neuropathy, and subacute combined degeneration of the spinal cord. Risk groups include strict vegans, elderly patients, those with pernicious anemia, and patients on long-term metformin or PPIs.",
                            DisplayName = "Vitamin B12 (Cobalamin)",
                            Name = "Vitamin B12",
                            Panel = "Vitamins & Minerals"
                        },
                        new
                        {
                            Id = 38,
                            ClinicalContext = "Folate is required for nucleotide synthesis and cell division. Deficiency causes macrocytic megaloblastic anemia and is a critical risk factor for neural tube defects in early pregnancy. Causes include poor diet, malabsorption, alcoholism, and medications (methotrexate, phenytoin).",
                            DisplayName = "Folate (Folic Acid)",
                            Name = "Folate",
                            Panel = "Vitamins & Minerals"
                        },
                        new
                        {
                            Id = 39,
                            ClinicalContext = "Serum iron reflects circulating iron bound to transferrin. Low serum iron with low ferritin confirms iron deficiency. Low serum iron with normal or high ferritin suggests anemia of chronic disease. Iron should be interpreted alongside TIBC and ferritin for full iron status assessment.",
                            DisplayName = "Serum Iron",
                            Name = "Iron",
                            Panel = "Vitamins & Minerals"
                        },
                        new
                        {
                            Id = 40,
                            ClinicalContext = "TIBC reflects the blood's capacity to bind iron, primarily via transferrin. Elevated TIBC with low iron and low ferritin is characteristic of iron deficiency anemia. Low TIBC with elevated ferritin suggests anemia of chronic disease or iron overload.",
                            DisplayName = "Total Iron Binding Capacity (TIBC)",
                            Name = "TIBC",
                            Panel = "Vitamins & Minerals"
                        },
                        new
                        {
                            Id = 41,
                            ClinicalContext = "Magnesium is essential for neuromuscular function, enzyme activity, and cardiac stability. Hypomagnesemia causes muscle cramps, arrhythmias, and refractory hypokalemia. It is common in alcoholism, malabsorption, and with diuretic use. Critically low levels can precipitate ventricular arrhythmias.",
                            DisplayName = "Magnesium (Mg)",
                            Name = "Magnesium",
                            Panel = "Vitamins & Minerals"
                        },
                        new
                        {
                            Id = 42,
                            ClinicalContext = "Zinc is a cofactor for hundreds of enzymes and is critical for immune function, wound healing, and taste/smell. Deficiency causes dermatitis, alopecia, impaired wound healing, and immune dysfunction. Risk groups include those with poor dietary intake, malabsorption, or chronic diarrhea.",
                            DisplayName = "Zinc (Zn)",
                            Name = "Zinc",
                            Panel = "Vitamins & Minerals"
                        });
                });

            modelBuilder.Entity("LabReferenceApi.Models.ReferenceRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BiomarkerId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CriticalHigh")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("CriticalLow")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("HighNormal")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("LowNormal")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer");

                    b.Property<string>("SexFilter")
                        .HasColumnType("text");

                    b.Property<decimal?>("SiConversionFactor")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("SiUnit")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BiomarkerId", "SexFilter", "MinAge", "MaxAge");

                    b.ToTable("ReferenceRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BiomarkerId = 1,
                            CriticalHigh = 30.0m,
                            CriticalLow = 2.0m,
                            HighNormal = 11.0m,
                            LowNormal = 4.5m,
                            SiConversionFactor = 1.0m,
                            SiUnit = "10^9/L",
                            Unit = "10^3/uL"
                        },
                        new
                        {
                            Id = 2,
                            BiomarkerId = 2,
                            CriticalHigh = 7.0m,
                            CriticalLow = 2.5m,
                            HighNormal = 5.9m,
                            LowNormal = 4.5m,
                            MinAge = 18,
                            SexFilter = "male",
                            SiConversionFactor = 1.0m,
                            SiUnit = "10^12/L",
                            Unit = "10^6/uL"
                        },
                        new
                        {
                            Id = 3,
                            BiomarkerId = 2,
                            CriticalHigh = 7.0m,
                            CriticalLow = 2.5m,
                            HighNormal = 5.2m,
                            LowNormal = 4.0m,
                            MinAge = 18,
                            SexFilter = "female",
                            SiConversionFactor = 1.0m,
                            SiUnit = "10^12/L",
                            Unit = "10^6/uL"
                        },
                        new
                        {
                            Id = 4,
                            BiomarkerId = 3,
                            CriticalHigh = 20.0m,
                            CriticalLow = 7.0m,
                            HighNormal = 17.5m,
                            LowNormal = 13.5m,
                            MinAge = 18,
                            SexFilter = "male",
                            SiConversionFactor = 10.0m,
                            SiUnit = "g/L",
                            Unit = "g/dL"
                        },
                        new
                        {
                            Id = 5,
                            BiomarkerId = 3,
                            CriticalHigh = 20.0m,
                            CriticalLow = 7.0m,
                            HighNormal = 16.0m,
                            LowNormal = 12.0m,
                            MinAge = 18,
                            SexFilter = "female",
                            SiConversionFactor = 10.0m,
                            SiUnit = "g/L",
                            Unit = "g/dL"
                        },
                        new
                        {
                            Id = 6,
                            BiomarkerId = 4,
                            CriticalHigh = 60.0m,
                            CriticalLow = 21.0m,
                            HighNormal = 53.0m,
                            LowNormal = 41.0m,
                            MinAge = 18,
                            SexFilter = "male",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 7,
                            BiomarkerId = 4,
                            CriticalHigh = 60.0m,
                            CriticalLow = 21.0m,
                            HighNormal = 46.0m,
                            LowNormal = 36.0m,
                            MinAge = 18,
                            SexFilter = "female",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 8,
                            BiomarkerId = 5,
                            CriticalHigh = 1000.0m,
                            CriticalLow = 50.0m,
                            HighNormal = 400.0m,
                            LowNormal = 150.0m,
                            SiConversionFactor = 1.0m,
                            SiUnit = "10^9/L",
                            Unit = "10^3/uL"
                        },
                        new
                        {
                            Id = 9,
                            BiomarkerId = 6,
                            HighNormal = 100.0m,
                            LowNormal = 80.0m,
                            Unit = "fL"
                        },
                        new
                        {
                            Id = 10,
                            BiomarkerId = 7,
                            HighNormal = 33.0m,
                            LowNormal = 27.0m,
                            Unit = "pg"
                        },
                        new
                        {
                            Id = 11,
                            BiomarkerId = 8,
                            CriticalHigh = 38.0m,
                            HighNormal = 36.0m,
                            LowNormal = 32.0m,
                            Unit = "g/dL"
                        },
                        new
                        {
                            Id = 12,
                            BiomarkerId = 9,
                            HighNormal = 14.5m,
                            LowNormal = 11.5m,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 13,
                            BiomarkerId = 10,
                            CriticalHigh = 160.0m,
                            CriticalLow = 120.0m,
                            HighNormal = 145.0m,
                            LowNormal = 136.0m,
                            SiConversionFactor = 1.0m,
                            SiUnit = "mmol/L",
                            Unit = "mEq/L"
                        },
                        new
                        {
                            Id = 14,
                            BiomarkerId = 11,
                            CriticalHigh = 6.5m,
                            CriticalLow = 2.5m,
                            HighNormal = 5.1m,
                            LowNormal = 3.5m,
                            SiConversionFactor = 1.0m,
                            SiUnit = "mmol/L",
                            Unit = "mEq/L"
                        },
                        new
                        {
                            Id = 15,
                            BiomarkerId = 12,
                            CriticalHigh = 120.0m,
                            CriticalLow = 80.0m,
                            HighNormal = 107.0m,
                            LowNormal = 98.0m,
                            SiConversionFactor = 1.0m,
                            SiUnit = "mmol/L",
                            Unit = "mEq/L"
                        },
                        new
                        {
                            Id = 16,
                            BiomarkerId = 13,
                            CriticalHigh = 40.0m,
                            CriticalLow = 10.0m,
                            HighNormal = 29.0m,
                            LowNormal = 22.0m,
                            SiConversionFactor = 1.0m,
                            SiUnit = "mmol/L",
                            Unit = "mEq/L"
                        },
                        new
                        {
                            Id = 17,
                            BiomarkerId = 14,
                            CriticalHigh = 13.0m,
                            CriticalLow = 7.0m,
                            HighNormal = 10.5m,
                            LowNormal = 8.5m,
                            SiConversionFactor = 0.25m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 18,
                            BiomarkerId = 15,
                            CriticalHigh = 100.0m,
                            HighNormal = 20.0m,
                            LowNormal = 7.0m,
                            SiConversionFactor = 0.357m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 19,
                            BiomarkerId = 16,
                            CriticalHigh = 10.0m,
                            HighNormal = 1.3m,
                            LowNormal = 0.7m,
                            MinAge = 18,
                            SexFilter = "male",
                            SiConversionFactor = 88.4m,
                            SiUnit = "umol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 20,
                            BiomarkerId = 16,
                            CriticalHigh = 10.0m,
                            HighNormal = 1.1m,
                            LowNormal = 0.5m,
                            MinAge = 18,
                            SexFilter = "female",
                            SiConversionFactor = 88.4m,
                            SiUnit = "umol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 21,
                            BiomarkerId = 17,
                            CriticalLow = 15.0m,
                            HighNormal = 200.0m,
                            LowNormal = 60.0m,
                            Unit = "mL/min/1.73m2"
                        },
                        new
                        {
                            Id = 22,
                            BiomarkerId = 18,
                            CriticalHigh = 500.0m,
                            CriticalLow = 40.0m,
                            HighNormal = 99.0m,
                            LowNormal = 70.0m,
                            SiConversionFactor = 0.05551m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 23,
                            BiomarkerId = 19,
                            CriticalHigh = 1000.0m,
                            HighNormal = 40.0m,
                            LowNormal = 10.0m,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 24,
                            BiomarkerId = 20,
                            CriticalHigh = 1000.0m,
                            HighNormal = 56.0m,
                            LowNormal = 7.0m,
                            SexFilter = "male",
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 25,
                            BiomarkerId = 20,
                            CriticalHigh = 1000.0m,
                            HighNormal = 45.0m,
                            LowNormal = 7.0m,
                            SexFilter = "female",
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 26,
                            BiomarkerId = 21,
                            HighNormal = 147.0m,
                            LowNormal = 44.0m,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 27,
                            BiomarkerId = 22,
                            CriticalHigh = 15.0m,
                            HighNormal = 1.2m,
                            LowNormal = 0.1m,
                            SiConversionFactor = 17.1m,
                            SiUnit = "umol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 28,
                            BiomarkerId = 23,
                            HighNormal = 8.2m,
                            LowNormal = 6.3m,
                            SiConversionFactor = 10.0m,
                            SiUnit = "g/L",
                            Unit = "g/dL"
                        },
                        new
                        {
                            Id = 29,
                            BiomarkerId = 24,
                            CriticalLow = 2.0m,
                            HighNormal = 5.0m,
                            LowNormal = 3.5m,
                            SiConversionFactor = 10.0m,
                            SiUnit = "g/L",
                            Unit = "g/dL"
                        },
                        new
                        {
                            Id = 30,
                            BiomarkerId = 25,
                            CriticalHigh = 300.0m,
                            HighNormal = 200.0m,
                            LowNormal = 0.0m,
                            SiConversionFactor = 0.02586m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 31,
                            BiomarkerId = 26,
                            CriticalHigh = 190.0m,
                            HighNormal = 130.0m,
                            LowNormal = 0.0m,
                            SiConversionFactor = 0.02586m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 32,
                            BiomarkerId = 27,
                            CriticalLow = 25.0m,
                            HighNormal = 200.0m,
                            LowNormal = 40.0m,
                            SexFilter = "male",
                            SiConversionFactor = 0.02586m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 33,
                            BiomarkerId = 27,
                            CriticalLow = 25.0m,
                            HighNormal = 200.0m,
                            LowNormal = 50.0m,
                            SexFilter = "female",
                            SiConversionFactor = 0.02586m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 34,
                            BiomarkerId = 28,
                            CriticalHigh = 500.0m,
                            HighNormal = 150.0m,
                            LowNormal = 0.0m,
                            SiConversionFactor = 0.01129m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 35,
                            BiomarkerId = 29,
                            HighNormal = 130.0m,
                            LowNormal = 0.0m,
                            SiConversionFactor = 0.02586m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 36,
                            BiomarkerId = 30,
                            CriticalHigh = 10.0m,
                            CriticalLow = 0.1m,
                            HighNormal = 4.0m,
                            LowNormal = 0.4m,
                            MaxAge = 60,
                            MinAge = 18,
                            Unit = "mIU/L"
                        },
                        new
                        {
                            Id = 37,
                            BiomarkerId = 30,
                            CriticalHigh = 10.0m,
                            CriticalLow = 0.1m,
                            HighNormal = 5.5m,
                            LowNormal = 0.4m,
                            MinAge = 60,
                            Unit = "mIU/L"
                        },
                        new
                        {
                            Id = 38,
                            BiomarkerId = 31,
                            HighNormal = 4.2m,
                            LowNormal = 2.3m,
                            SiConversionFactor = 1.536m,
                            SiUnit = "pmol/L",
                            Unit = "pg/mL"
                        },
                        new
                        {
                            Id = 39,
                            BiomarkerId = 32,
                            HighNormal = 1.8m,
                            LowNormal = 0.8m,
                            SiConversionFactor = 12.87m,
                            SiUnit = "pmol/L",
                            Unit = "ng/dL"
                        },
                        new
                        {
                            Id = 40,
                            BiomarkerId = 33,
                            CriticalHigh = 100.0m,
                            HighNormal = 1.0m,
                            LowNormal = 0.0m,
                            Unit = "mg/L"
                        },
                        new
                        {
                            Id = 41,
                            BiomarkerId = 34,
                            HighNormal = 15.0m,
                            LowNormal = 0.0m,
                            SexFilter = "male",
                            Unit = "mm/hr"
                        },
                        new
                        {
                            Id = 42,
                            BiomarkerId = 34,
                            HighNormal = 20.0m,
                            LowNormal = 0.0m,
                            SexFilter = "female",
                            Unit = "mm/hr"
                        },
                        new
                        {
                            Id = 43,
                            BiomarkerId = 35,
                            CriticalLow = 10.0m,
                            HighNormal = 336.0m,
                            LowNormal = 24.0m,
                            SexFilter = "male",
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 44,
                            BiomarkerId = 35,
                            CriticalLow = 10.0m,
                            HighNormal = 307.0m,
                            LowNormal = 11.0m,
                            SexFilter = "female",
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 45,
                            BiomarkerId = 36,
                            CriticalHigh = 150.0m,
                            CriticalLow = 10.0m,
                            HighNormal = 100.0m,
                            LowNormal = 30.0m,
                            SiConversionFactor = 0.4m,
                            SiUnit = "nmol/L",
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 46,
                            BiomarkerId = 37,
                            CriticalLow = 100.0m,
                            HighNormal = 900.0m,
                            LowNormal = 200.0m,
                            SiConversionFactor = 0.7378m,
                            SiUnit = "pmol/L",
                            Unit = "pg/mL"
                        },
                        new
                        {
                            Id = 47,
                            BiomarkerId = 38,
                            CriticalLow = 2.0m,
                            HighNormal = 17.0m,
                            LowNormal = 2.7m,
                            SiConversionFactor = 0.4413m,
                            SiUnit = "nmol/L",
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 48,
                            BiomarkerId = 39,
                            CriticalLow = 20.0m,
                            HighNormal = 170.0m,
                            LowNormal = 60.0m,
                            SexFilter = "male",
                            SiConversionFactor = 0.179m,
                            SiUnit = "umol/L",
                            Unit = "mcg/dL"
                        },
                        new
                        {
                            Id = 49,
                            BiomarkerId = 39,
                            CriticalLow = 20.0m,
                            HighNormal = 145.0m,
                            LowNormal = 37.0m,
                            SexFilter = "female",
                            SiConversionFactor = 0.179m,
                            SiUnit = "umol/L",
                            Unit = "mcg/dL"
                        },
                        new
                        {
                            Id = 50,
                            BiomarkerId = 40,
                            HighNormal = 370.0m,
                            LowNormal = 250.0m,
                            SiConversionFactor = 0.179m,
                            SiUnit = "umol/L",
                            Unit = "mcg/dL"
                        },
                        new
                        {
                            Id = 51,
                            BiomarkerId = 41,
                            CriticalHigh = 3.5m,
                            CriticalLow = 1.2m,
                            HighNormal = 2.2m,
                            LowNormal = 1.7m,
                            SiConversionFactor = 0.4114m,
                            SiUnit = "mmol/L",
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 52,
                            BiomarkerId = 42,
                            CriticalLow = 30.0m,
                            HighNormal = 120.0m,
                            LowNormal = 60.0m,
                            SiConversionFactor = 0.153m,
                            SiUnit = "umol/L",
                            Unit = "mcg/dL"
                        });
                });

            modelBuilder.Entity("LabReferenceApi.Models.ReferenceRange", b =>
                {
                    b.HasOne("LabReferenceApi.Models.Biomarker", "Biomarker")
                        .WithMany("ReferenceRanges")
                        .HasForeignKey("BiomarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biomarker");
                });

            modelBuilder.Entity("LabReferenceApi.Models.Biomarker", b =>
                {
                    b.Navigation("ReferenceRanges");
                });
#pragma warning restore 612, 618
        }
    }
}
